### ISSUE TITLE
Proposal for a generalised approach for data sync error suppression

### ISSUE THREAD

**Issue by kevindew** [alphagov/govuk_app_config#152]
A big pain point for GOV.UK error monitoring is any code that runs in integration and staging during the nightly database sync. This process drops the current database and then imports a new database, code that executes during this time (such as scheduled tasks) may error if it has to interact with the database. These errors can flood Sentry and make it difficult to spot genuine errors. 

An approach we've taken to working around this scenario in [Content Publisher](https://github.com/alphagov/content-publisher/blob/d088576a1a121d5f1d3492babcf727243e32ab09/config/initializers/govuk_error.rb#L8-L16) and [Email Alert API](https://github.com/alphagov/email-alert-api/blob/f0c61539f7244bdb52db54d277a46412b728d642/config/initializers/govuk_error.rb#L8-L18) is to suppress these errors using the [`should_capture`](https://docs.sentry.io/clients/ruby/config/#optional-settings) callback. Now there is interest in using this for a third application, which seems to indicate a good time to generalise. Naturally it'd be better if we were in a situation where apps didn't run and error during the sync but I'm considering this out of scope for this issue.

Just copying the code from a previous implementation into govuk_app_config seems a flawed approach for a few reasons:

- It only supports Postgres / currently requires postgres
- It clobbers any existing usages of the should_capture callback
- Fetching environment from the sentry environment variable feels a bit tangential
- The data sync times need to be kept in sync with puppet
- It's very hard to test

So to merge this into govuk_app_config I propose that we build a generalised approach.

Ideas for this would be:

## A configuration variable to specify exceptions to exclude during data sync

Similar to how we have [config.excluded_exceptions](https://github.com/alphagov/govuk_app_config/blob/08b3d0659337834313cf757d6f332535dfbb395b/lib/govuk_app_config/configure.rb#L10) it'd be good to have a sibling of `config.govuk_data_sync_excluded_exceptions` where an array of class names can be provided. We could have "PG::Error" included there by default and apps can add their own ones if they like.

To do this we may have to use a [delegator pattern](https://ruby-doc.org/stdlib-2.5.1/libdoc/delegate/rdoc/SimpleDelegator.html) to add extra behaviour to the [Raven config object](https://github.com/alphagov/govuk_app_config/blob/08b3d0659337834313cf757d6f332535dfbb395b/lib/govuk_app_config/govuk_error.rb#L15-L17).

## Create an environment variable for data sync environments

We can replace the hard-coded times and the need to use the `SENTRY_CURRENT_ENV` to determine whether we're in a data sync environment. The contents of this variable can tell us the times it runs from and until and it's mere presence could tell us whether we're in an environment with a data sync period.

As a suggestion we could call it `GOVUK_DATA_SYNC_PERIOD` and have contents such as "22:00-08:00". This could then be parsed and used to work out if we're in a data sync when an error occurs.

Puppet can be used to set this based on [this data](https://github.com/alphagov/govuk-puppet/blob/4bcf837e0dc4f48be59716921841307dfa291ebe/modules/govuk_data_sync_in_progress/manifests/init.pp) hopefully it can be abstracted from the class it is defined in.

## Implementation

With the above the next things we could do is:

- write the code for this in a testable class
- handle parsing the environment variable at app start up time rather than at the point of an error (as a problem with this may make apps break in messy ways if it occurs at runtime)
- work out if we there is a way we can [re-use code from raven](https://github.com/getsentry/raven-ruby/blob/3826f07499d2b1c227d1db394e48c19f1f6e6633/lib/raven/utils/exception_cause_chain.rb) to determine exception cause (the [Content Publisher approach](https://github.com/alphagov/content-publisher/blob/c701fd0c57c47e071f226aa6c817fb45a63506e0/config/initializers/govuk_error.rb#L9-L10) is pretty crude)
- work out how to maintain any existing `should_capture` configuration when initialising

/cc @thomasleese

**Comment by thomasleese** [comment]
Thanks @kevindew for this comprehensive write up. I've [written it up as a card for Platform Health](https://trello.com/c/rAlvGlSp/1833-ignore-data-sync-errors-in-govukappconfig). /cc @ChrisBAshton

**Comment by ChrisBAshton** [comment]
Hello 👋  I'm working on this at the moment. RE:

> work out how to maintain any existing `should_capture` configuration when initialising

This feels like misplaced effort to me, as [the only two instances of `should_capture`](https://github.com/search?q=org%3Aalphagov+should_capture&type=code) are in content-publisher and email-alert-api, which we will no longer need  once their behaviours are encapsulated in govuk_app_config. I can imagine a future scenario where we'd want some specific `should_capture` behaviour in an app, but perhaps that's something that can be tackled when the time comes, rather than us building functionality that might never be used?

My hesitation is because I can't think of a way of allowing apps to specify `should_capture` without it overwriting the govuk_app_config version, so my approach would have been to write our own callback, e.g. `app_specific_should_capture`, which we would call _inside_ `govuk_app_config`'s `should_capture` something along the lines of:

```ruby
config.should_capture = proc {
  config.app_specific_should_capture() if defined?(config.app_specific_should_capture)
  # then the govuk_app_config data sync stuff here
}
```

I can build something like this but, as I say, perhaps better to leave it until it's needed? What do you think?

**Comment by kevindew** [comment]
> Hello 👋 I'm working on this at the moment. RE:
> 
> > work out how to maintain any existing `should_capture` configuration when initialising
> 
> This feels like misplaced effort to me, as [the only two instances of `should_capture`](https://github.com/search?q=org%3Aalphagov+should_capture&type=code) are in content-publisher and email-alert-api, which we will no longer need once their behaviours are encapsulated in govuk_app_config. I can imagine a future scenario where we'd want some specific `should_capture` behaviour in an app, but perhaps that's something that can be tackled when the time comes, rather than us building functionality that might never be used?
> 
Sure, that makes sense. It seems reasonable to skip it for now, but would be good to have thought about a reasonable way for it to be done - since it's quite a useful bit of functionality.

> My hesitation is because I can't think of a way of allowing apps to specify `should_capture` without it overwriting the govuk_app_config version, so my approach would have been to write our own callback, e.g. `app_specific_should_capture`, which we would call _inside_ `govuk_app_config`'s `should_capture` something along the lines of:
> 
> ```ruby
> config.should_capture = proc {
>   config.app_specific_should_capture() if defined?(config.app_specific_should_capture)
>   # then the govuk_app_config data sync stuff here
> }
> ```
> 
> I can build something like this but, as I say, perhaps better to leave it until it's needed? What do you think?

I think the tricky part around this is deciding what the config object that is yielded to `GovukError.configure` is. From you saying you can't think of a way of allowing it that implies to me that you're assuming that will continue to be the raven config object. From my contrived perspective this seems an invalid assumption as we're going to need the object that is yielded to have a means to configure the list of data sync errors to ignore. Without this we may have to approach configuring them in a rather hacky way (unless I'm missing an obvious alternative). So I suspected we might want something like [SimpleDelegator](https://ruby-doc.org/stdlib-2.5.1/libdoc/delegate/rdoc/SimpleDelegator.html) on the yielded config object which could accept the extra data. If we used something like that we could also have a `def should_capture=(closure)` method that knows how to combine a user provided should_capture with the default one.
